### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taiyoslime** [taiyoslime/taiyoslime.github.io#1]
- [ ] デザイン変更

---
- [ ] アニメーションのパフォーマンスの改善
- [ ]  message box の改善

---
- [ ] HTML リファクタリング(slim等)
- [ ] CSS リファクタリング(sass+compass,BEM設計)
- [ ] Javascript リファクタリング(jQuery依存解決とその他)
